"""personal information table

Revision ID: 0449fb25f240
Revises: d53bbcc7406d
Create Date: 2024-12-10 16:00:18.846738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0449fb25f240'
down_revision: Union[str, None] = 'd53bbcc7406d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PersonalInfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('profession', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PersonalInfo_email'), 'PersonalInfo', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PersonalInfo_email'), table_name='PersonalInfo')
    op.drop_table('PersonalInfo')
    # ### end Alembic commands ###
